{"name": "Login with Invalid Password", "status": "broken", "statusDetails": {"message": "NameError: name 'allure' is not defined", "trace": "self = <testcases.test_login.Test_001_Login object at 0x1052f34d0>\n\n    @allure.title(\"Login with Invalid Password\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_invalid_password(self):\n        self.logger.info(\"********** Testing Invalid Password Login **********\")\n        self.lp = LoginPage(self.driver)\n        try:\n>           self.lp.login(self.username, \"invalid_password\")\n\ntestcases/test_login.py:42: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npageobjects/LoginPage.py:43: in login\n    self.enter_username(username)\npageobjects/LoginPage.py:19: in enter_username\n    WebDriverWait(self.driver, 10).until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"cb73091be792e372273a3c1b35beb241\")>\nmethod = <function presence_of_element_located.<locals>._predicate at 0x10543b880>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Wait until the method returns a value that is not False.\n    \n        Calls the method provided with the driver as an argument until the\n        return value does not evaluate to ``False``.\n    \n        Parameters:\n        -----------\n        method: callable(WebDriver)\n            - A callable object that takes a WebDriver instance as an argument.\n    \n        message: str\n            - Optional message for :exc:`TimeoutException`\n    \n        Return:\n        -------\n        object: T\n            - The result of the last call to `method`\n    \n        Raises:\n        -------\n        TimeoutException\n            - If 'method' does not return a truthy value within the WebDriverWait\n            object's timeout\n    \n        Example:\n        --------\n        >>> from selenium.webdriver.common.by import By\n        >>> from selenium.webdriver.support.ui import WebDriverWait\n        >>> from selenium.webdriver.support import expected_conditions as EC\n    \n        # Wait until an element is visible on the page\n        >>> wait = WebDriverWait(driver, 10)\n        >>> element = wait.until(EC.visibility_of_element_located((By.ID, \"exampleId\")))\n        >>> print(element.text)\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            if time.monotonic() > end_time:\n                break\n            time.sleep(self._poll)\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       0   chromedriver                        0x0000000100d82a54 cxxbridge1$str$ptr + 2803960\nE       1   chromedriver                        0x0000000100d7acf0 cxxbridge1$str$ptr + 2771860\nE       2   chromedriver                        0x00000001008c6864 cxxbridge1$string$len + 93028\nE       3   chromedriver                        0x000000010090d410 cxxbridge1$string$len + 382736\nE       4   chromedriver                        0x000000010094e480 cxxbridge1$string$len + 649088\nE       5   chromedriver                        0x00000001009017ec cxxbridge1$string$len + 334572\nE       6   chromedriver                        0x0000000100d47ccc cxxbridge1$str$ptr + 2562928\nE       7   chromedriver                        0x0000000100d4af98 cxxbridge1$str$ptr + 2575932\nE       8   chromedriver                        0x0000000100d282c4 cxxbridge1$str$ptr + 2433384\nE       9   chromedriver                        0x0000000100d4b810 cxxbridge1$str$ptr + 2578100\nE       10  chromedriver                        0x0000000100d192f0 cxxbridge1$str$ptr + 2371988\nE       11  chromedriver                        0x0000000100d6b57c cxxbridge1$str$ptr + 2708512\nE       12  chromedriver                        0x0000000100d6b708 cxxbridge1$str$ptr + 2708908\nE       13  chromedriver                        0x0000000100d7a93c cxxbridge1$str$ptr + 2770912\nE       14  libsystem_pthread.dylib             0x0000000190d59c0c _pthread_start + 136\nE       15  libsystem_pthread.dylib             0x0000000190d54b80 thread_start + 8\n\n/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/selenium/webdriver/support/wait.py:146: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <testcases.test_login.Test_001_Login object at 0x1052f34d0>\n\n    @allure.title(\"Login with Invalid Password\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_invalid_password(self):\n        self.logger.info(\"********** Testing Invalid Password Login **********\")\n        self.lp = LoginPage(self.driver)\n        try:\n            self.lp.login(self.username, \"invalid_password\")\n            error_message = WebDriverWait(self.driver, 10).until(\n                EC.presence_of_element_located(\n                    (By.XPATH, \"//*[@id='app']/div[1]/div/div[1]/div/div[2]/div[2]/div/div[1]/div[1]/p\"))\n            )\n            assert \"Invalid credentials\" in error_message.text\n            self.logger.info(\"Invalid password test PASSED\")\n        except Exception as e:\n>           self._handle_test_failure(\"invalid_password\", e)\n\ntestcases/test_login.py:50: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <testcases.test_login.Test_001_Login object at 0x1052f34d0>, test_name = 'invalid_password', exception = TimeoutException()\n\n    def _handle_test_failure(self, test_name, exception):\n        \"\"\"Helper method to handle test failures\"\"\"\n        timestamp = time.strftime(\"%Y%m%d-%H%M%S\")\n        screenshot_path = f\"/Users/vivekkumar/screenshots/test_{test_name}_failed_{timestamp}.png\"\n        self.driver.save_screenshot(screenshot_path)\n        self.logger.error(f\"Test {test_name} FAILED. Screenshot saved to: {screenshot_path}\")\n        self.logger.error(f\"Exception: {str(exception)}\")\n    \n        # âœ… Attach screenshot to Allure\n>       allure.attach.file(screenshot_path, name=f\"{test_name}_screenshot\", attachment_type=allure.attachment_type.PNG)\nE       NameError: name 'allure' is not defined\n\ntestcases/test_login.py:107: NameError"}, "attachments": [{"name": "Failure Screenshot", "source": "e1666d44-b6a6-4514-b60d-c55452919578-attachment.png", "type": "image/png"}, {"name": "log", "source": "f60d6a70-12c1-4cde-ac42-af408e701c2c-attachment.txt", "type": "text/plain"}], "start": 1746532085097, "stop": 1746532095597, "uuid": "d4a2cda9-e216-4abf-87d5-f59c80c56b6c", "historyId": "aba918a04925777e096b92283807eaf8", "testCaseId": "aba918a04925777e096b92283807eaf8", "fullName": "testcases.test_login.Test_001_Login#test_invalid_password", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_001_Login"}, {"name": "host", "value": "viveks-MacBook-Air-2.local"}, {"name": "thread", "value": "18660-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}